// <auto-generated />
using System;
using FCG.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FCG.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260101000000_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FCG.Domain.Entities.Game", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Description").IsRequired().HasMaxLength(2000).HasColumnType("nvarchar(2000)");
                    b.Property<string>("Genre").IsRequired().HasMaxLength(80).HasColumnType("nvarchar(80)");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<decimal>("Price").HasColumnType("decimal(18,2)");
                    b.Property<DateTime>("ReleaseDate").HasColumnType("datetime2");
                    b.Property<string>("Title").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Title");
                    b.ToTable("Games", (string)null);
                });

            modelBuilder.Entity("FCG.Domain.Entities.Promotion", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<decimal>("DiscountPercentage").HasColumnType("decimal(5,2)");
                    b.Property<DateTime>("EndsAt").HasColumnType("datetime2");
                    b.Property<Guid>("GameId").HasColumnType("uniqueidentifier");
                    b.Property<bool>("IsActive").HasColumnType("bit");
                    b.Property<DateTime>("StartsAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("GameId");
                    b.ToTable("Promotions", (string)null);
                });

            modelBuilder.Entity("FCG.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id").HasColumnType("uniqueidentifier");
                    b.Property<DateTime>("CreatedAt").HasColumnType("datetime2");
                    b.Property<string>("Email").IsRequired().HasMaxLength(200).HasColumnType("nvarchar(200)");
                    b.Property<string>("Name").IsRequired().HasMaxLength(150).HasColumnType("nvarchar(150)");
                    b.Property<string>("PasswordHash").IsRequired().HasMaxLength(500).HasColumnType("nvarchar(500)");
                    b.Property<int>("Role").HasColumnType("int");
                    b.Property<DateTime?>("UpdatedAt").HasColumnType("datetime2");
                    b.HasKey("Id");
                    b.HasIndex("Email").IsUnique();
                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("FCG.Domain.Entities.Promotion", b =>
                {
                    b.HasOne("FCG.Domain.Entities.Game", "Game")
                        .WithMany("Promotions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                    b.Navigation("Game");
                });

            modelBuilder.Entity("FCG.Domain.Entities.Game", b =>
                {
                    b.Navigation("Promotions");
                });
#pragma warning restore 612, 618
        }
    }
}
